sudo: true
language: c
before_install:
  - (wget https://github.com/detailyang/zint/archive/2.4.2-memory.tar.gz && tar -zxf 2.4.2-memory.tar.gz && cd zint-2.4.2-memory && cmake . && sudo make install)
  - sudo apt-get install libev-dev build-essential cpanminus libzbar-dev libbarcode-zbar-perl perlmagick
  - wget https://github.com/lighttpd/weighttp/archive/weighttp-0.4.tar.gz
  - tar -zxf weighttp-0.4.tar.gz
  - (cd weighttp-weighttp-0.4 && ./autogen.sh && ./configure && make && sudo make install)
  - wget http://nginx.org/download/nginx-1.9.15.tar.gz
  - tar -zxf nginx-1.9.15.tar.gz
script:
  - (cd nginx-1.9.15 && ./configure --add-module=/home/travis/build/detailyang/ngx_http_barcode && make -j4 && sudo make install)
  - sudo cpanm Test::Nginx
  - (export PERL_MM_USE_DEFAULT=1 && git clone https://github.com/detailyang/test-nginx.git && cd test-nginx && perl Makefile.PL && sudo make uninstall && sudo make install)
  - make test

deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
